name: Deploy frontend application
"on":
  push:
    branches:
      - prod
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: prepare the docker-compose run
        run: |
          ls -l

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ahsanfrontend:latest

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: prepare the docker-compose run
        run: |
          mkdir deploy-ahsan-frontend
          cp docker-compose.yml deploy-ahsan-frontend/docker-compose.yml
          cd deploy-ahsan-frontend
          docker-compose -H ${{ secrets.HOST_SERVER }} down
          docker-compose -H ${{ secrets.HOST_SERVER }} pull
          docker-compose -H ${{ secrets.HOST_SERVER }} up -d
